### ISSUE TITLE
Request: open discussions

### ISSUE THREAD

**Issue by jongfeel** [sang-a-kim/art-lover#3]
github settings에 discussions를 열 수 있습니다. 열어 주시면 좋을 것 같아요.

그 이후에는 discussions 에서 논의 내용을 적어 보면 좋겠습니다.
첫 이슈인

- #1 

이 내용이 task나 bug fix의 느낌으로 쓰는 issue 보다는 discussions로 쓰는게 더 낫거든요.

**Comment by sang-a-kim** [comment]
discussion에 논의 내용 옮겨놓았습니다!
